
services:
  mongodb:
    image: mongo:7.0
    container_name: prequal-mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: prequal
    volumes:
      - mongodb_data:/data/db
    networks:
      - prequal-sonar-network

  backend:
    build: .
    container_name: prequal-backend
    ports:
      - "8081:8080"
    volumes:
      - ~/PReQual-script/tmp:/data:ro
    depends_on:
      - mongodb
    networks:
      - prequal-sonar-network

volumes:
  mongodb_data:

networks:
  prequal-sonar-network:
    driver: bridge